#!/usr/bin/env python3
"""Small, standard-library-only hand-written SLOC and quality-gate audit.

The implementation intentionally uses lexical approximations rather than a
third-party parser.  It is suitable for a P0 gate: every read, parse, and
configuration failure is visible and fail-closed, while generated/vendor/cache
files are kept in separate buckets.
"""
import argparse
import collections
import datetime as _datetime
import hashlib
import io
import json
import math
import os
import re
import sys
import tokenize
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


SCHEMA_VERSION = "1.0"
EXIT_OK = 0
EXIT_FINDINGS = 1
EXIT_ERROR = 2

MANUAL_SLOC_TARGET = 560_000
DEFAULT_MAX_FILE_LINES = 800
DEFAULT_MAX_PACKAGE_LINES = 8_000
DEFAULT_DUPLICATE_THRESHOLD = 0.90

# These directories are not part of the source accounting.  Cache files are
# counted in the separate cache bucket when encountered, but never enter manual.
TREE_SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".venv",
    "venv",
    "node_modules",
    "coverage",
    ".cache",
}
CACHE_DIR_NAMES = {"cache", "caches", "tmp", "temp", "build", "dist", "coverage", ".coverage"}
VENDOR_DIR_NAMES = {"vendor", "third_party", "third-party", "external", "thirdparty"}
GENERATED_DIR_NAMES = {
    "generated",
    "gen",
    "gen-src",
    "autogen",
    "auto_generated",
    "code_generated",
    "protobuf",
    "openapi_generated",
}
SOURCE_EXTENSIONS = {
    ".go",
    ".py",
    ".pyi",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".java",
    ".kt",
    ".kts",
    ".scala",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".hpp",
    ".cs",
    ".rs",
    ".rb",
    ".php",
    ".swift",
    ".sh",
    ".bash",
    ".ps1",
    ".proto",
    ".cue",
}
DOCUMENT_EXTENSIONS = {
    ".md",
    ".markdown",
    ".rst",
    ".txt",
    ".json",
    ".jsonl",
    ".ndjson",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".xml",
    ".html",
    ".htm",
    ".css",
    ".scss",
    ".sql",
    ".csv",
    ".tsv",
    ".graphql",
    ".gql",
}
TEXT_BASENAMES = {"Dockerfile", "Makefile", "README", "LICENSE"}

PHASE_TARGETS = {
    "P0": 28_000,
    "P1": 86_000,
    "P2": 60_000,
    "P3": 106_000,
    "P4": 94_000,
    "P5": 24_000,
    "P6": 66_000,
    "P7": 76_000,
    "P8": 20_000,
}
PHASES = tuple(PHASE_TARGETS)


class AuditInputError(Exception):
    """A file or tree could not be read/lexed safely."""


class PlanError(Exception):
    """The plan file is unreadable or is not JSONL."""


@dataclass(frozen=True)
class FileRecord:
    path: str
    category: str
    language: str
    sloc: int
    physical_lines: int
    package: str
    reason: str
    digest: str


@dataclass(frozen=True)
class TokenWindow:
    path: str
    line: int
    tokens: tuple[str, ...]


# ---------------------------------------------------------------------------
# Classification and lexical SLOC


def _read_text(path: Path) -> str:
    try:
        data = path.read_bytes()
    except Exception as exc:
        raise AuditInputError("file-unreadable") from exc
    if b"\x00" in data[:8192]:
        raise UnicodeDecodeError("utf-8", data[:1], 0, 1, "binary-file")
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise AuditInputError("file-encoding-invalid") from exc


def _digest_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            for block in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(block)
    except OSError as exc:
        raise AuditInputError("file-unreadable") from exc
    return digest.hexdigest()


def _is_generated_name(path: Path) -> bool:
    name = path.name.lower()
    # Handwritten Protobuf contracts are source. Generated stubs use a
    # separate suffix such as .pb.go or _pb2.py.
    if name.endswith(".proto"):
        return False
    if name.endswith((".min.js", ".min.css", ".map")):
        return True
    if re.search(r"(?:^|[._-])(?:pb|generated|autogen)(?:[._-]|$)", name):
        return True
    if name.endswith(("_pb2.py", "_pb2_grpc.py", "_pb.js", "_pb.d.ts", ".pb.go", ".g.dart")):
        return True
    if "generated" in name or "autogen" in name:
        return True
    return False


def _has_generated_header(text: str) -> bool:
    header = "\n".join(text.splitlines()[:8]).lower()
    markers = (
        "code generated",
        "do not edit",
        "@generated",
        "generated by",
        "autogenerated",
        "automatically generated",
    )
    return any(marker in header for marker in markers)


def _is_test_path(path: Path) -> bool:
    parts = {part.lower() for part in path.parts}
    if parts.intersection({"test", "tests", "__tests__", "spec", "specs"}):
        return True
    name = path.name.lower()
    return bool(
        name.startswith("test_")
        or name.endswith("_test.go")
        or name.endswith("_test.py")
        or ".test." in name
        or ".spec." in name
        or name in {"conftest.py", "test.java", "test.kt"}
    )


def _package_for(relative: str) -> str:
    path = Path(relative)
    parent = path.parent.as_posix()
    return "." if parent == "." else parent


def _language_for(path: Path) -> str:
    suffix = path.suffix.lower().lstrip(".")
    if suffix in {"py", "pyi"}:
        return "python"
    if suffix == "go":
        return "go"
    if suffix in {"ts", "tsx", "js", "jsx"}:
        return "javascript"
    if suffix in {"java", "kt", "kts", "scala"}:
        return "jvm"
    if suffix in {"c", "h", "cc", "cpp", "hpp"}:
        return "c-family"
    if suffix in {"rs"}:
        return "rust"
    if suffix in {"rb"}:
        return "ruby"
    if suffix in {"php"}:
        return "php"
    if suffix in {"swift"}:
        return "swift"
    if suffix in {"sh", "bash", "ps1"}:
        return "shell"
    if suffix in {"proto", "cue"}:
        return "contract"
    return suffix or "text"


def classify_file(path: str | os.PathLike[str], text: str | None = None) -> dict[str, Any]:
    """Classify a path using path, generated headers, and extension signals."""
    file_path = Path(path)
    parts = {part.lower() for part in file_path.parts}
    suffix = file_path.suffix.lower()
    name = file_path.name
    if any(part in TREE_SKIP_DIRS for part in parts):
        return {
            "category": "cache",
            "language": _language_for(file_path),
            "reason": "cache-directory",
            "manual": False,
        }
    if any(part in CACHE_DIR_NAMES for part in parts):
        return {
            "category": "cache",
            "language": _language_for(file_path),
            "reason": "cache-directory",
            "manual": False,
        }
    if any(part in GENERATED_DIR_NAMES for part in parts) or _is_generated_name(file_path):
        return {
            "category": "generated",
            "language": _language_for(file_path),
            "reason": "generated-path-or-name",
            "manual": False,
        }
    if text is not None and _has_generated_header(text):
        return {
            "category": "generated",
            "language": _language_for(file_path),
            "reason": "generated-header",
            "manual": False,
        }
    if any(part in VENDOR_DIR_NAMES for part in parts):
        return {
            "category": "vendor",
            "language": _language_for(file_path),
            "reason": "vendor-directory",
            "manual": False,
        }
    if suffix in SOURCE_EXTENSIONS or name in TEXT_BASENAMES:
        category = "test" if _is_test_path(file_path) else "production"
        return {
            "category": category,
            "language": _language_for(file_path),
            "reason": "handwritten-source",
            "manual": True,
        }
    if suffix in DOCUMENT_EXTENSIONS:
        return {
            "category": "document",
            "language": _language_for(file_path),
            "reason": "document-or-config",
            "manual": False,
        }
    return {
        "category": "unknown",
        "language": _language_for(file_path),
        "reason": "unsupported-file-type",
        "manual": False,
    }


def _python_code_lines(text: str) -> set[int]:
    """Return physical line numbers containing non-comment, non-string tokens."""
    try:
        tokens = tokenize.generate_tokens(io.StringIO(text).readline)
        meaningful: set[int] = set()
        ignored = {
            tokenize.COMMENT,
            tokenize.STRING,
            tokenize.NL,
            tokenize.NEWLINE,
            tokenize.INDENT,
            tokenize.DEDENT,
            tokenize.ENDMARKER,
            tokenize.ENCODING,
        }
        for token in tokens:
            if token.type in ignored:
                continue
            if getattr(token, "string", "").strip():
                meaningful.add(token.start[0])
        return meaningful
    except (tokenize.TokenError, IndentationError, SyntaxError) as exc:
        raise AuditInputError("python-lex-error") from exc


def _generic_code_lines(text: str) -> set[int]:
    """A conservative comment/string stripper for non-Python source."""
    meaningful: set[int] = set()
    state = "code"  # code, line_comment, block_comment, string
    quote = ""
    escaped = False
    line = 1
    has_token = False
    index = 0
    while index < len(text):
        char = text[index]
        nxt = text[index + 1] if index + 1 < len(text) else ""
        if char == "\n":
            if state == "line_comment":
                state = "code"
            if has_token:
                meaningful.add(line)
            has_token = False
            line += 1
            state = "code" if state != "block_comment" else state
            index += 1
            continue
        if state == "code":
            if char == "/" and nxt == "/":
                state = "line_comment"
                index += 2
                continue
            if char == "/" and nxt == "*":
                state = "block_comment"
                index += 2
                continue
            if char in {"'", '"', "`"}:
                state = "string"
                quote = char
                escaped = False
                index += 1
                continue
            if not char.isspace():
                has_token = True
            index += 1
            continue
        if state == "line_comment":
            index += 1
            continue
        if state == "block_comment":
            if char == "*" and nxt == "/":
                state = "code"
                index += 2
            else:
                index += 1
            continue
        if state == "string":
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                state = "code"
            index += 1
    if has_token:
        meaningful.add(line)
    return meaningful


def count_sloc(text: str, path: str | os.PathLike[str] = "fixture.py") -> int:
    """Count physical lines with a meaningful token using a lexical pass."""
    if not isinstance(text, str):
        raise TypeError("text must be a string")
    suffix = Path(path).suffix.lower()
    if suffix in {".py", ".pyi"} or str(path).endswith(".py"):
        return len(_python_code_lines(text))
    return len(_generic_code_lines(text))


def _duplicate_source(path: str, text: str) -> str:
    """Drop protocol boilerplate before duplicate detection.

    Protobuf package/import/option headers are fixed contract structure.
    Import lines are also excluded so two tools can share a standard-library
    prelude without hiding copied business logic.
    """
    if path.endswith(".proto"):
        kept = []
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith(("syntax ", "package ", "import ", "option ")):
                continue
            if re.match(r"(?:repeated\s+)?(?:string|bool|bytes|int32|int64|uint32|uint64)\s+\w+\s*=\s*\d+\s*;", stripped):
                continue
            kept.append(line)
        return "\n".join(kept)
    if path.endswith(".py"):
        kept = []
        skipping_import = False
        for line in text.splitlines():
            if skipping_import:
                if ")" in line:
                    skipping_import = False
                continue
            if line.startswith(("import ", "from ")):
                if "(" in line and ")" not in line:
                    skipping_import = True
                continue
            kept.append(line)
        return "\n".join(kept)
    return text


def _normalise_tokens(text: str, path: str | os.PathLike[str]) -> list[tuple[str, int]]:
    text = _duplicate_source(str(path), text)
    suffix = Path(path).suffix.lower()
    if suffix in {".py", ".pyi"}:
        try:
            raw_tokens = tokenize.generate_tokens(io.StringIO(text).readline)
            result: list[tuple[str, int]] = []
            ignored = {
                tokenize.COMMENT,
                tokenize.STRING,
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.INDENT,
                tokenize.DEDENT,
                tokenize.ENDMARKER,
                tokenize.ENCODING,
            }
            for token in raw_tokens:
                if token.type in ignored:
                    continue
                value = token.string
                if token.type == tokenize.NAME:
                    value = "ID"
                elif token.type == tokenize.NUMBER:
                    value = "NUM"
                result.append((value, token.start[0]))
            return result
        except (tokenize.TokenError, IndentationError, SyntaxError) as exc:
            raise AuditInputError("python-lex-error") from exc
    # A language-neutral lexical approximation for duplicate candidates.
    pattern = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*|\d+(?:\.\d+)?|===|!==|==|!=|<=|>=|&&|\|\||\S")
    result = []
    for match in pattern.finditer(text):
        value = match.group(0)
        if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value):
            value = "ID"
        elif re.fullmatch(r"\d+(?:\.\d+)?", value):
            value = "NUM"
        result.append((value, text.count("\n", 0, match.start()) + 1))
    return result


def find_duplicate_blocks(
    file_texts: Mapping[str, str],
    threshold: float = DEFAULT_DUPLICATE_THRESHOLD,
    window: int = 50,
) -> list[dict[str, Any]]:
    """Find repeated token windows without including source text in the result."""
    if not 0.0 <= threshold <= 1.0:
        raise ValueError("threshold must be between 0 and 1")
    if window < 10:
        raise ValueError("window must be at least 10 tokens")
    groups: dict[tuple[str, ...], list[TokenWindow]] = collections.defaultdict(list)
    for path, text in sorted(file_texts.items()):
        tokens = _normalise_tokens(text, path)
        if len(tokens) < window:
            continue
        # Use overlapping windows so a block boundary does not hide a copy.
        step = max(1, window // 2)
        for start in range(0, len(tokens) - window + 1, step):
            selected = tokens[start : start + window]
            signature = tuple(value for value, _ in selected)
            groups[signature].append(
                TokenWindow(path, selected[0][1], tuple(value for value, _ in selected))
            )
    reports: list[dict[str, Any]] = []
    for signature, locations in groups.items():
        if len(locations) < 2:
            continue
        # Keep a bounded, deterministic set of locations in a very repetitive
        # file while still proving that the repeated block exists.
        unique_locations: list[TokenWindow] = []
        seen: set[tuple[str, int]] = set()
        for location in locations:
            marker = (location.path, location.line)
            if marker not in seen:
                seen.add(marker)
                unique_locations.append(location)
        token_set = set(signature)
        similarity = 1.0
        # Exact normalised signatures are intentionally a high-confidence
        # finding.  For mixed groups, compare token sets to apply the gate.
        if len(unique_locations) > 1:
            left = token_set
            right = token_set
            union = left | right
            similarity = len(left & right) / len(union) if union else 0.0
        if similarity > threshold:
            reports.append(
                {
                    "similarity": round(similarity, 3),
                    "window_tokens": window,
                    "locations": [
                        {"path": item.path, "line": item.line} for item in unique_locations[:20]
                    ],
                    "occurrences": len(unique_locations),
                }
            )
    # A repeated signature can be encountered at several offsets; collapse
    # reports that point to the same pair of files and token count.
    unique: dict[tuple[Any, ...], dict[str, Any]] = {}
    for report in reports:
        locations = report["locations"]
        marker = (report["window_tokens"], tuple(sorted((x["path"], x["line"]) for x in locations)))
        unique[marker] = report
    return sorted(
        unique.values(),
        key=lambda item: (
            item["locations"][0]["path"],
            item["locations"][0]["line"],
            item["locations"][-1]["path"],
            item["locations"][-1]["line"],
        ),
    )


# ---------------------------------------------------------------------------
# Plan parsing and reconciliation


def _is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def load_plan(path: str | os.PathLike[str]) -> list[dict[str, Any]]:
    plan_path = Path(path)
    try:
        text = plan_path.read_text(encoding="utf-8-sig")
    except Exception as exc:
        raise PlanError("plan-unreadable") from exc
    rows: list[dict[str, Any]] = []
    for line_number, line in enumerate(text.splitlines(), 1):
        if not line.strip():
            continue
        try:
            item = json.loads(line)
        except Exception as exc:
            raise PlanError("plan-json-invalid") from exc
        if not isinstance(item, dict):
            raise PlanError("plan-row-invalid")
        rows.append(item)
    if not rows:
        raise PlanError("plan-empty")
    return rows


def _plan_dag_ok(rows: Sequence[Mapping[str, Any]]) -> bool:
    ids = {str(row.get("id")) for row in rows}
    indegree = {item: 0 for item in ids}
    children: dict[str, list[str]] = collections.defaultdict(list)
    for row in rows:
        parent = str(row.get("id"))
        for dependency in row.get("depends_on", []) or []:
            dep = str(dependency)
            if dep not in ids:
                return False
            indegree[parent] += 1
            children[dep].append(parent)
    queue = collections.deque(sorted(item for item, degree in indegree.items() if degree == 0))
    visited = 0
    while queue:
        node = queue.popleft()
        visited += 1
        for child in sorted(children.get(node, [])):
            indegree[child] -= 1
            if indegree[child] == 0:
                queue.append(child)
    return visited == len(ids)


def validate_plan(rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    """Validate the shared batch contract and calculate phase totals."""
    issues: list[str] = []
    ids: list[str] = []
    phase_totals: dict[str, dict[str, int]] = {
        phase: {"batches": 0, "loc_target": 0, "production_loc": 0, "test_loc": 0}
        for phase in PHASES
    }
    id_pattern = re.compile(r"^ATLAS-P([0-8])-(\d{4})$")
    numeric_ids: list[int] = []
    for index, row in enumerate(rows, 1):
        row_id = row.get("id")
        if not isinstance(row_id, str):
            issues.append(f"row-{index}-id-invalid")
            continue
        ids.append(row_id)
        match = id_pattern.fullmatch(row_id)
        if not match:
            issues.append(f"{row_id}-id-format-invalid")
        else:
            numeric_ids.append(int(match.group(2)))
            phase = row.get("phase")
            if phase != "P" + match.group(1):
                issues.append(f"{row_id}-phase-id-mismatch")
        phase = row.get("phase")
        if phase not in PHASE_TARGETS:
            issues.append(f"{row_id}-phase-invalid")
        elif not isinstance(row.get("module"), str) or not row.get("module"):
            issues.append(f"{row_id}-module-invalid")
        for field in ("depends_on", "inputs", "outputs", "acceptance", "reviewer"):
            if field not in row:
                issues.append(f"{row_id}-{field}-missing")
        depends = row.get("depends_on", [])
        if not isinstance(depends, list) or any(not isinstance(dep, str) for dep in depends):
            issues.append(f"{row_id}-dependencies-invalid")
        for field in ("loc_target", "production_loc", "test_loc"):
            if field in row and not _is_int(row[field]):
                issues.append(f"{row_id}-{field}-invalid")
        loc = row.get("loc_target")
        if _is_int(loc) and not 800 <= loc <= 2_500:
            issues.append(f"{row_id}-loc-range-invalid")
        production = row.get("production_loc")
        test = row.get("test_loc")
        if _is_int(production) and _is_int(test) and _is_int(loc) and production + test != loc:
            issues.append(f"{row_id}-loc-split-invalid")
        if phase in phase_totals and _is_int(loc):
            phase_totals[phase]["batches"] += 1
            phase_totals[phase]["loc_target"] += loc
            if _is_int(production):
                phase_totals[phase]["production_loc"] += production
            if _is_int(test):
                phase_totals[phase]["test_loc"] += test
    if len(set(ids)) != len(ids):
        issues.append("duplicate-batch-id")
    if numeric_ids and sorted(numeric_ids) != list(range(1, len(numeric_ids) + 1)):
        issues.append("batch-sequence-not-contiguous")
    for row in rows:
        row_id = row.get("id")
        if not isinstance(row_id, str):
            continue
        for dependency in row.get("depends_on", []) or []:
            if isinstance(dependency, str):
                dep_match = id_pattern.fullmatch(dependency)
                current_match = id_pattern.fullmatch(row_id)
                if dep_match and current_match and int(dependency.rsplit("-", 1)[1]) >= int(row_id.rsplit("-", 1)[1]):
                    issues.append(f"{row_id}-dependency-not-earlier")
    if not _plan_dag_ok(rows):
        issues.append("dependency-cycle")
    if len(rows) < 340 or len(rows) > 400:
        issues.append("batch-count-out-of-contract-range")
    for phase, target in PHASE_TARGETS.items():
        if phase_totals[phase]["loc_target"] != target:
            issues.append(f"{phase}-loc-target-mismatch")
    total = sum(item["loc_target"] for item in phase_totals.values())
    if total != 560_000:
        issues.append("total-loc-target-mismatch")
    return {
        "batches": len(rows),
        "total_loc": total,
        "production_loc": sum(item["production_loc"] for item in phase_totals.values()),
        "test_loc": sum(item["test_loc"] for item in phase_totals.values()),
        "phases": [
            {
                "phase": phase,
                **phase_totals[phase],
                "target": PHASE_TARGETS[phase],
                "delta": phase_totals[phase]["loc_target"] - PHASE_TARGETS[phase],
            }
            for phase in PHASES
        ],
        "issues": sorted(set(issues)),
        "status": "pass" if not issues else "fail",
    }


# ---------------------------------------------------------------------------
# Tree audit
