#!/usr/bin/env python3
"""Temporary synthetic fixtures for handwritten SLOC classification."""
from __future__ import annotations

import subprocess
import tempfile
import unittest
import json
import sys
import importlib.util
from pathlib import Path


LOCAUDIT_SCANNER = Path(__file__).resolve().parent / "scan.py"
sys.dont_write_bytecode = True


def load_locaudit():
    location = "atlas_loc_gate"
    spec = importlib.util.spec_from_file_location(location, LOCAUDIT_SCANNER)
    if spec is None or spec.loader is None:
        raise RuntimeError("locaudit-unavailable")
    loaded_module = importlib.util.module_from_spec(spec)
    sys.modules[location] = loaded_module
    spec.loader.exec_module(loaded_module)
    return loaded_module


def run_scanner(root: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-B", str(LOCAUDIT_SCANNER), "--root", str(root), *extra],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )


class LocAuditTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.scanner = load_locaudit()

    def test_normal_fixture_counts_comments_strings_and_test_separately(self) -> None:
        source = "# header\n\ndef add(left, right):\n    return left + right\n"
        test_source = "# test\n\ndef test_add():\n    assert add(1, 2) == 3\n"
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "service.py").write_text(source, encoding="utf-8")
            (root / "test_service.py").write_text(test_source, encoding="utf-8")
            result = run_scanner(root)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            report = json.loads(result.stdout)
            self.assertEqual(report["status"], "pass")
            self.assertEqual(report["manual"]["production"], 2)
            self.assertEqual(report["manual"]["test"], 2)
            self.assertEqual(report["manual"]["total"], 4)
            self.assertEqual(report["generated"]["files"], 0)
            self.assertEqual(report["vendor"]["files"], 0)
            self.assertEqual(
                self.scanner.count_sloc("# only\n\n", "empty.py"),
                0,
            )

    def test_generated_vendor_and_cache_are_separate_buckets(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "generated").mkdir()
            (root / "generated" / "api.py").write_text(
                "# Code generated by a tool; DO NOT EDIT.\nvalue = 1\n", encoding="utf-8"
            )
            vendor = root / "vendor"
            vendor.mkdir()
            (vendor / "library.py").write_text("value = 1\n", encoding="utf-8")
            cache = root / "cache"
            cache.mkdir()
            (cache / "compiled.py").write_text("cached = 1\n", encoding="utf-8")
            result = run_scanner(root)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            report = json.loads(result.stdout)
            self.assertEqual(report["generated"]["files"], 1)
            self.assertEqual(report["vendor"]["files"], 1)
            self.assertEqual(report["caches"]["files"], 1)
            self.assertEqual(report["manual"]["total"], 0)
            categories = {item["path"]: item["category"] for item in report["files"]}
            self.assertEqual(categories["generated/api.py"], "generated")
            self.assertEqual(categories["vendor/library.py"], "vendor")
            self.assertEqual(categories["cache/compiled.py"], "cache")

    def test_invalid_plan_json_is_configuration_error(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "service.py").write_text("value = 1\n", encoding="utf-8")
            plan = root / "batches.jsonl"
            plan.write_text('{"id": "not-json"\n', encoding="utf-8")
            result = run_scanner(root, "--plan", str(plan))
            self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
            report = json.loads(result.stdout)
            self.assertEqual(report["status"], "error")
            self.assertEqual(report["errors"][0]["code"], "plan-json-invalid")

    def test_duplicate_blocks_and_oversized_file_are_reported(self) -> None:
        repeated = "\n".join("value_{0} = {0}".format(index) for index in range(70)) + "\n"
        oversized = "\n".join("value_{0} = {0}".format(index) for index in range(801)) + "\n"
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "one.py").write_text(repeated, encoding="utf-8")
            (root / "two.py").write_text(repeated, encoding="utf-8")
            (root / "oversized.py").write_text(oversized, encoding="utf-8")
            result = run_scanner(root)
            self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
            report = json.loads(result.stdout)
            self.assertEqual(report["status"], "fail")
            gate_ids = {gate["id"] for gate in report["gates"] if gate["status"] == "fail"}
            self.assertIn("duplicate-blocks", gate_ids)
            self.assertIn("file-line-limit", gate_ids)
            self.assertTrue(report["duplicates"], report)
            self.assertTrue(
                any(item["path"] == "oversized.py" for item in report["gates"][2]["files"]),
                report["gates"],
            )

    def test_plan_mode_emits_phase_reconciliation_even_for_incomplete_fixture(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "service.py").write_text("value = 1\n", encoding="utf-8")
            plan = root / "batches.jsonl"
            plan.write_text(
                json.dumps(
                    {
                        "id": "ATLAS-P0-0001",
                        "phase": "P0",
                        "module": "fixture",
                        "title": "synthetic",
                        "depends_on": [],
                        "inputs": [],
                        "outputs": [],
                        "loc_target": 800,
                        "production_loc": 400,
                        "test_loc": 400,
                        "acceptance": ["fixture check"],
                        "reviewer": "test-owner",
                    }
                )
                + "\n",
                encoding="utf-8",
            )
            result = run_scanner(root, "--plan", str(plan))
            self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
            report = json.loads(result.stdout)
            self.assertIn("plan", report)
            self.assertIn("batch-plan-reconciliation", {item["id"] for item in report["gates"]})
            self.assertIn("P0-loc-target-mismatch", report["plan"]["issues"])


if __name__ == "__main__":
    unittest.main()
